# Generated by Django 4.2.6 on 2023-12-02 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ForeignKey(default='default_cover.jpg', on_delete=django.db.models.deletion.CASCADE, related_name='article_cover', to='api.image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(default='default_avatar.jpg', on_delete=django.db.models.deletion.CASCADE, related_name='user_avatar', to='api.image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ForeignKey(default='default_cover.jpg', on_delete=django.db.models.deletion.CASCADE, related_name='user_cover', to='api.image'),
        ),
    ]
