# Generated by Django 4.2.6 on 2023-12-03 18:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default=api.models.generateName, max_length=32),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(default=api.models.generateName, max_length=32),
        ),
    ]
