# Generated by Django 4.2.6 on 2023-12-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_image_image_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='创建这个板块的人很懒,连板块介绍都没有!'),
        ),
    ]
