# Generated by Django 4.2.6 on 2023-12-03 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_article_created_time_alter_article_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='author',
            new_name='likedUser',
        ),
    ]
