# Generated by Django 4.2.6 on 2023-12-03 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_author_like_likeduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='commentUser',
        ),
    ]
