# Generated by Django 4.2.6 on 2023-12-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_author_comment_commentuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField(default='暂无回复')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
