# Generated by Django 4.2.6 on 2023-12-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_uservideo_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='response',
            field=models.TextField(default=''),
        ),
    ]
