# Generated by Django 4.2.6 on 2023-12-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_feedbackpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='response',
        ),
    ]
