# Generated by Django 4.2.6 on 2023-12-06 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_feedback_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.image'),
        ),
    ]
